version: '3.8'
services:
  node-app:
    depends_on: 
      - mongo
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mikee
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  redis: 
    image: redis
    
volumes:
  mongo-db:
