version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    depends_on: 
      - mongo
    build: .
    image: michaelibe/node-app
    environment:
      - PORT=3000
  

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mikee
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  redis: 
    image: redis
    
volumes:
  mongo-db:
